deployment:
  tasks:
    - export DEPLOYPATH=/home/c1290081c/public_html/wp-content/plugins/paniers
    - /bin/cp -Ruv html $DEPLOYPATH/
    - /bin/cp -uv autoupdate.php $DEPLOYPATH/
    - /bin/cp -uv paniers.* $DEPLOYPATH/
    - /bin/cp -uv composer.* $DEPLOYPATH/
    - cd $DEPLOYPATH
    - composer update
