deployment:
  tasks:
    - export DEPLOYPATH=/home/c1290081c/public_html/wp-content/plugins/paniers
    - /bin/cp -Ruv html $DEPLOYPATH/
    - /bin/cp -Ruv vendor $DEPLOYPATH/
    - /bin/cp -uv paniers.* $DEPLOYPATH/
